### ISSUE TITLE
Unidentified microcontroller

### ISSUE THREAD

**Issue by DaveRichmond** [tomverbeure/cisco-hwic-3g-cdma#1]
Since there doesn't really seem to be a good place to discuss this board, I recently acquired the 3G GSM version. One difference I've noticed is that the chip that could be a microcontroller (tssop14 package) leads a little down a rabbit hole on this board.
Sorry the board is a little dusty, it's how it came and i haven't taken the time to clean it yet. Here's the ![microcontroller](https://user-images.githubusercontent.com/2533709/69513747-e89adf00-0f9c-11ea-907a-4a10cce60021.jpg) seems to have "CV9622" on it, which after a little bit of searching, only seems to be referenced on a list of discontinued NXP parts (https://www.nxp.com/wcm_documents/products/eol/dn62_a.pdf). P83LPC913FDH/CV9622, is a replacement part for a customer specific "ROM PART of the LPC900 Family". I think it's safe to assume that's this part. So if I'm reading that right, it was a custom chip for one customer, but P89LPC913 (https://www.nxp.com/docs/en/data-sheet/P89LPC912_913_914.pdf) is probably very similar.
Obviously doesn't make this part of the board any more useful, but hopefully its useful.

**Comment by tomverbeure** [comment]
Hello Dave,

Nice!

On some of my boards, this chip is marked MXQ3311, but on others it's CV9606. Which is shown right underneath the CV9622 in the table that you're linked to.

So it looks like this is some tiny 8051 controller with tiny amount of flash and RAM.

This further confirms that there is no bitstream configuration EEPROM on the PCB.

I made a decent amount of progress mapping out the PCI to FPGA pins, the NOR flash pins, and soldering a NOR flash onto one of my many PCBs (I have 4 of this type, and a whole bunch of other Cisco cards.) :-)

I just dumped the boundary scan chain values while the board is inside the Cisco router:
https://github.com/tomverbeure/cisco-hwic-3g-cdma/blob/master/bscan/ep2c35_report.txt

This should help with identifying a number of other pins as well. Especially the XTAL input of the ISP1564HL: it's driven by the FPGA, but not directly so standard ohm-ing out doesn't work.

Tom
