### ISSUE TITLE
Mating Connector Part Number for EHWIC connector

### ISSUE THREAD

**Issue by FordPrefect1024** [tomverbeure/cisco-hwic-3g-cdma#2]
Not really an issue, but I wanted to have a place to discuss this....

I have been looking for the mating connector part # (or a way to build a footprint and manually stuff a connector) and I've not been able to locate one that this board can easily plug into.  once you remove the i/o plate, there are good places to securely fasten the boards together too.

It looks like it should be possible to make a 'personality board' with signal conditioning, aux components (ADC, etc...), power, and bitstream capabiliites, but it won't be very useful without a mating connector strategy... Is there a connector we can purchase for this?  Or are scrap routers the cheapest solution?

**Comment by tomverbeure** [comment]
At this very moment, I'm designing a footprint in KiCAD. :-)

It's a combination of a 1x15 2.54mm pin header and a 2x34 1.27mm pin header.

The 1x15 2.54mm header is thru-hole, with some pins removed. The 2x34 1.27mm pin header will probably be SMT, but I might still change that to thru-hole as well.

Search for the following term on AliExpress:

10PCS SMD SMT 2*2/3/4/5/6/7/8/9/10/12/16/20/40/ PIN double row male PIN HEADER 1.27MM PITCH Strip Connector 2X/6/8/10/20

**Comment by tomverbeure** [comment]
Just to be clear: I'm not designing a connector, but a small PCB with the pin headers arranged in HWIC configuration. Current plan is to include an ATTiny85 for bitstream loading, but that might changed to an STM32 Blue Pill. TBD.

**Comment by FordPrefect1024** [comment]
Great!  

I was thinking two boards would be required.. so it would end up being parallel to the personality board.  Sort of a breakout-to-connector and then connector to board.  (So that the little adapter board would be largely reusable and the customizable part for other ehwics in the future).  Also, it wouldn't require the larger base board for just using the fpga... (Sort of like you have already done on the bench.). But whatever... There's enough info here that I could do that on my own anyway :). Don't let my ramblings slow ya down.

Thanks for collecting all this here.
